"""Add BarberSchedule model

Revision ID: 999660c90056
Revises: 05b23a1de76b
Create Date: 2025-11-16 18:54:58.466802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999660c90056'
down_revision = '05b23a1de76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barber_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barber_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barber_schedules')
    # ### end Alembic commands ###
