"""Add vacation dates to barber

Revision ID: e6afa2e9bac8
Revises: 2b348f5f9664
Create Date: 2025-11-19 19:35:13.039925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6afa2e9bac8'
down_revision = '2b348f5f9664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vacation_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('vacation_end', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.drop_column('vacation_end')
        batch_op.drop_column('vacation_start')

    # ### end Alembic commands ###
